# Generated by Django 5.0.1 on 2024-07-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
